export const notifications = [
  {
    id: "n1",
    title: "Security · access review batch",
    titleAr: "الأمن · مراجعة الصلاحيات",
    body: "14 exceptions require manager sign-off by Friday.",
    bodyAr: "14 استثناء يحتاج اعتماد المدير قبل الجمعة.",
    time: "Now",
    timeAr: "الآن",
    category: "security" as const,
    unread: true,
  },
  {
    id: "n2",
    title: "Reach Assistant",
    titleAr: "مساعد وصل",
    body: "Meeting summary ready — Portfolio review.",
    bodyAr: "ملخص الاجتماع جاهز — مراجعة المحفظة.",
    time: "32m ago",
    timeAr: "قبل 32 دقيقة",
    category: "ai" as const,
    unread: true,
  },
  {
    id: "n3",
    title: "Operations",
    titleAr: "العمليات",
    body: "Incident INC-8891 correlated with upstream DNS drift.",
    bodyAr: "الحادثة INC-8891 مرتبطة بانحراف في DNS العلوي.",
    time: "1h ago",
    timeAr: "قبل ساعة",
    category: "operations" as const,
    unread: false,
  },
  {
    id: "n4",
    title: "Employee Hub",
    titleAr: "مركز الموظف",
    body: "Expense report ER-4422 marked ready for payroll.",
    bodyAr: "تقرير المصاريف ER-4422 جاهز للرواتب.",
    time: "Yesterday",
    timeAr: "أمس",
    category: "employee" as const,
    unread: false,
  },
]
